Repository WattRex/Battery-Cycler-Drivers, pull requests merged in 2023-10, with the labels that each got.

#46 Drv db
  code/drv_db/src/wattrex_driver_db/__init__.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_cache.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_master.py
  code/drv_db/src/wattrex_driver_db/drv_db_types.py
  code/drv_db/tests/example_cache.py
Labels: enhancement

#45 Drv CAN
  code/drv_can/src/can_sniffer/can_sniffer.py
Labels: enhancement

#50 Drv base
  code/drv_base/LICENSE.txt
  code/drv_base/MANIFEST.in
  code/drv_base/README.md
  code/drv_base/pyproject.toml
  code/drv_base/requirements.txt
  code/drv_base/src/wattrex_driver_base/__init__.py
  code/drv_base/src/wattrex_driver_base/drv_base_status.py
Labels: good first issue

#48 Drv flow
  code/drv_flow/README.md
  code/drv_flow/requirements.txt
  code/drv_flow/resources/flowmeter_arduino.ino
  code/drv_flow/src/wattrex_driver_flow/__init__.py
  code/drv_flow/src/wattrex_driver_flow/drv_flow.py
  code/drv_flow/src/wattrex_driver_flow/drv_flow_writter.py
  code/drv_flow/tests/example.py
Labels: enhancement

#52 Drv db
  code/drv_db/src/wattrex_driver_db/__init__.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_base.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_cache.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_master.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_utils.py
Labels: enhancement

#51 Drv mqtt
  code/drv_mqtt/LICENSE.txt
  code/drv_mqtt/MANIFEST.in
  code/drv_mqtt/README.md
  code/drv_mqtt/pyproject.toml
  code/drv_mqtt/requirements.txt
  code/drv_mqtt/src/wattrex_driver_mqtt/__init__.py
  code/drv_mqtt/src/wattrex_driver_mqtt/drv_mqtt.py
  code/drv_mqtt/tests/example.py
Labels: good first issue

#53 drv mqtt
  code/drv_mqtt/src/wattrex_driver_mqtt/drv_mqtt.py
Labels: good first issue

#60 Update ORM CU: Name -> HostName
  .github/workflows/deploy_drivers_2_development.yml
  code/drv_db/src/wattrex_driver_db/drv_db_dao_master.py
  code/drv_db/src/wattrex_driver_db/drv_db_engine.py
Labels: bug
