Repository WattRex/Battery-Cycler-Drivers, pull requests merged in 2023-08, with the labels that each got.

#6 First version driver database
  .github/workflows/deploy_drivers_2_development.yml
  code/drv_db/LICENSE
  code/drv_db/MANIFEST.in
  code/drv_db/README.md
  code/drv_db/pyproject.toml
  code/drv_db/requirements.txt
  code/drv_db/src/battery_cycler_driver_db/__init__.py
  code/drv_db/src/battery_cycler_driver_db/drv_db_dao.py
  code/drv_db/src/battery_cycler_driver_db/drv_db_engine.py
  code/drv_db/src/battery_cycler_driver_db/drv_db_types.py
  code/sys_abs/sys_conf/__init__.py
  code/sys_abs/sys_conf/sys_conf.py
  code/sys_abs/sys_log/README.md
  code/sys_abs/sys_log/__init__.py
  code/sys_abs/sys_log/logginConfig.conf
  code/sys_abs/sys_log/sys_log.py
  code/sys_abs/sys_shd/README.md
  code/sys_abs/sys_shd/__init__.py
  code/sys_abs/sys_shd/sys_shd.py
Labels: good first issue

#7 Drv can
  code/drv_can/LICENSE.txt
  code/drv_can/MANIFEST.in
  code/drv_can/README.md
  code/drv_can/pyproject.toml
  code/drv_can/requirements.txt
  code/drv_can/src/can_sniffer/__init__.py
  code/drv_can/src/can_sniffer/can_sniffer.py
  code/drv_can/tests/example.py
Labels: good first issue

#9 Drv epc first deployment
  code/drv_epc/LICENSE.txt
  code/drv_epc/MANIFEST.in
  code/drv_epc/README.md
  code/drv_epc/example/epc0x0_data.csv
  code/drv_epc/example/epc0x10_data.csv
  code/drv_epc/example/epc0x20_data.csv
  code/drv_epc/example/epc0x2_data.csv
  code/drv_epc/example/epc0x30_data.csv
  code/drv_epc/example/epc1.txt
  code/drv_epc/example/epc3.txt
  code/drv_epc/example/epc4.txt
  code/drv_epc/example/epc5.txt
  code/drv_epc/example/epc6.txt
  code/drv_epc/example/epc7.txt
  code/drv_epc/example/epc8.txt
  code/drv_epc/pyproject.toml
  code/drv_epc/requirements.txt
  code/drv_epc/src/battery_cycler_drv_epc/__init__.py
  code/drv_epc/src/battery_cycler_drv_epc/drv_epc.py
  code/drv_epc/tests/README.md
  code/drv_epc/tests/example.py
  code/drv_epc/tests/example/epc0x0_data.csv
  code/drv_epc/tests/example/epc0x10_data.csv
  code/drv_epc/tests/example/epc0x20_data.csv
  code/drv_epc/tests/example/epc0x2_data.csv
  code/drv_epc/tests/example/epc0x30_data.csv
  code/drv_epc/tests/example/epc1.txt
  code/drv_epc/tests/example/epc3.txt
  code/drv_epc/tests/example/epc4.txt
  code/drv_epc/tests/example/epc5.txt
  code/drv_epc/tests/example/epc6.txt
  code/drv_epc/tests/example/epc7.txt
  code/drv_epc/tests/example/epc8.txt
Labels: good first issue

#11 Drv scpi
  code/drv_scpi/LICENSE.txt
  code/drv_scpi/MANIFEST.in
  code/drv_scpi/README.md
  code/drv_scpi/pyproject.toml
  code/drv_scpi/requirements.txt
  code/drv_scpi/src/scpi_sniffer/__init__.py
  code/drv_scpi/src/scpi_sniffer/drv_scpi_cmd.py
  code/drv_scpi/src/scpi_sniffer/drv_scpi_iface.py
  code/drv_scpi/src/scpi_sniffer/drv_scpi_node.py
  code/drv_scpi/tests/example.py
Labels: good first issue

#12 Name change
  code/drv_epc/pyproject.toml
  code/drv_epc/src/wattrex_driver_epc/__init__.py
  code/drv_epc/src/wattrex_driver_epc/drv_epc.py
Labels: QA

#13 Database name package change
  code/drv_db/pyproject.toml
  code/drv_db/src/wattrex_driver_db/__init__.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao.py
  code/drv_db/src/wattrex_driver_db/drv_db_engine.py
  code/drv_db/src/wattrex_driver_db/drv_db_types.py
Labels: QA

#15 Add reqs for drv_pwr
  code/drv_pwr/requirements.txt
Labels: good first issue

#16 Name change for drv_pwr driver
  code/drv_pwr/pyproject.toml
Labels: QA

#18 Add exclude
  code/drv_epc/MANIFEST.in
Labels: QA

#22 First version of DRV BK
  code/drv_bk/LICENSE.txt
  code/drv_bk/MANIFEST.in
  code/drv_bk/README.md
  code/drv_bk/pyproject.toml
  code/drv_bk/requirements.txt
  code/drv_bk/src/wattrex_driver_bk/__init__.py
  code/drv_bk/src/wattrex_driver_bk/drv_bk.py
  code/drv_bk/tests/example.py
Labels: good first issue

#23 First realease of DRV RS
  code/drv_rs/LICENSE.txt
  code/drv_rs/MANIFEST.in
  code/drv_rs/README.md
  code/drv_rs/pyproject.toml
  code/drv_rs/requirements.txt
  code/drv_rs/src/wattrex_driver_rs/__init__.py
  code/drv_rs/src/wattrex_driver_rs/drv_rs.py
  code/drv_rs/tests/example.py
Labels: good first issue

#25 Drv can solve sign in messages
  code/drv_can/pyproject.toml
  code/drv_can/src/can_sniffer/can_sniffer.py
Labels: bug

#28 Drv epc
  code/drv_epc/requirements.txt
  code/drv_epc/src/wattrex_driver_epc/drv_epc.py
  code/drv_epc/tests/example.py
Labels: enhancement

#29 Drv epc
  .vscode/.pylintrc
  code/drv_epc/src/wattrex_driver_epc/drv_epc.py
Labels: bug

#31 Drv ea
  code/drv_ea/src/wattrex_driver_ea/drv_ea.py
Labels: enhancement
