Repository WattRex/Battery-Cycler-Drivers, pull requests merged in 2023-11, with the labels that each got.

#61 First version of driver bms
  code/drv_bms/LICENSE.txt
  code/drv_bms/MANIFEST.in
  code/drv_bms/README.md
  code/drv_bms/pyproject.toml
  code/drv_bms/requirements.txt
  code/drv_bms/src/wattrex_driver_bms/__init__.py
  code/drv_bms/src/wattrex_driver_bms/drv_bms.py
  code/drv_bms/tests/config_file.yml
  code/drv_bms/tests/example.py
Labels: good first issue

#62 Drv db
  .github/workflows/deploy_drivers_2_development.yml
  code/drv_db/src/wattrex_driver_db/__init__.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_master.py
  code/drv_db/src/wattrex_driver_db/drv_db_types.py
Labels: enhancement

#63 Engine get a cred file and could get section of the cred file
  code/drv_db/src/wattrex_driver_db/drv_db_engine.py
  code/drv_db/tests/example_cache.py
  code/drv_db/tests/example_master.py
  code/drv_db/tests/example_master_cache.py
Labels: enhancement

#64 Drv db
  .github/workflows/deploy_drivers_2_development.yml
  code/drv_db/src/wattrex_driver_db/drv_db_engine.py
Labels: enhancement

#65 Add debug prints
  code/drv_db/src/wattrex_driver_db/drv_db_engine.py
Labels: enhancement

#66 drv flow
  code/drv_flow/src/wattrex_driver_flow/drv_flow.py
  code/drv_flow/tests/example.py
Labels: enhancement

#67 Fix field Power type and Add StatusID to Status Table in dao_base
  code/drv_db/src/wattrex_driver_db/drv_db_dao_base.py
Labels: bug

#68 Removed dev id
  code/drv_bms/src/wattrex_driver_bms/drv_bms.py
  code/drv_bms/tests/example.py
Labels: enhancement

#43 Drv epc
  code/drv_epc/requirements.txt
  code/drv_epc/src/wattrex_driver_epc/__init__.py
  code/drv_epc/src/wattrex_driver_epc/drv_epc_common.py
  code/drv_epc/src/wattrex_driver_epc/drv_epc_device.py
  code/drv_epc/tests/example.py
  code/drv_epc/tests/mini_example.py
Labels: enhancement

#69 Drv epc
  code/drv_epc/src/wattrex_driver_epc/drv_epc_device.py
  code/drv_epc/tests/example.py
Labels: enhancement

#70 Drv mqtt
  .github/workflows/deploy_drivers_2_development.yml
  code/drv_mqtt/src/wattrex_driver_mqtt/drv_mqtt.py
Labels: enhancement

#71 Add DrvDbConnStatusE import to __init__.py
  code/drv_db/src/wattrex_driver_db/__init__.py
Labels: bug

#72 Drv db
  code/drv_db/src/wattrex_driver_db/drv_db_engine.py
  code/drv_db/src/wattrex_driver_db/drv_db_types.py
  code/drv_db/tests/example_cache.py
  code/drv_db/tests/example_master.py
  code/drv_db/tests/example_master_cache.py
Labels: bug

#73 Removed warning declarative_base
  code/drv_db/requirements.txt
  code/drv_db/src/wattrex_driver_db/drv_db_dao_base.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_cache.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_master.py
Labels: enhancement

#75 DRV db
  code/drv_db/src/wattrex_driver_db/__init__.py
  code/drv_db/src/wattrex_driver_db/context.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_base.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_cache.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_master.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_utils.py
  code/drv_db/src/wattrex_driver_db/drv_db_engine.py
Labels: enhancement

#76 DRV CAN
  code/drv_can/src/can_sniffer/can_sniffer.py
  code/drv_can/src/can_sniffer/context.py
  code/drv_can/tests/example.py
Labels: enhancement

#77 DRV BMS
  code/drv_bms/src/wattrex_driver_bms/context.py
  code/drv_bms/src/wattrex_driver_bms/drv_bms.py
  code/drv_bms/tests/example.py
Labels: enhancement

#80 driver db
  code/drv_db/src/wattrex_driver_db/__init__.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_base.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_cache.py
  code/drv_db/src/wattrex_driver_db/drv_db_dao_master.py
Labels: bug, enhancement

#79 Drv EPC
  code/drv_epc/src/wattrex_driver_epc/context.py
  code/drv_epc/src/wattrex_driver_epc/drv_epc_common.py
  code/drv_epc/src/wattrex_driver_epc/drv_epc_device.py
Labels: bug, enhancement
